Shopify/lhm

lib/lhm/migrator.rb, spec/unit/migrator_spec.rb
Prevents this kind of thing:
```ruby
change_table :foo do |m|
m.add_index [:bar], name: 'bar'
end
```
```sql
create index `{:name=>"bar"}` on `lhmn_foo` (`bar`)
```
@arthurnn @camilo 
cc @sroysen @SingerWang
=> Raise an error when index name is invalid

bin/lhm-spec-grants.sh, bin/lhm-spec-setup-cluster.sh, lib/lhm/migrator.rb, spec/fixtures/no_charset.ddl, spec/fixtures/non_default_charset.ddl, spec/integration/integration_helper.rb, spec/integration/lhm_spec.rb
This will patch LHM to create all tables with `DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC` by default.  As long as a table has an LHM run on it at some point, it'll now be emoji friendly without us having to manually update it.
The code is pretty simple.  Normally when creating the new table, LHM takes the existing table's attributes and simply swaps its name with `lhmn_#{name}`.  This adds a regex that'll also swap the `DEFAULT CHARSET=x` with `DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC`  
Getting the integration tests passing was a bit of a nightmare, but I've finally got everything passing locally. 
Proof (from the integration tests):
```
CREATE TABLE `lhmn_users` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`reference` int(11) DEFAULT NULL,
`username` varchar(255) DEFAULT NULL,
`group` …
```
=> Create emoji friendly tables by default

bin/lhm-spec-grants.sh, lib/lhm/throttler/slave_lag.rb, spec/README.md, spec/unit/throttler/slave_lag_spec.rb
We've been intentionally raising here when you can't connect to a slave to check its lag during an LHM.  Which made sense... except we have servers that we know have some I/O issues and are lagging all the time, slowing down LHMs, and we'd like to be able to stop those.  Or if a reader simply dies or something... if that happens right now after you're 20 hours into an LHM then the whole thing blows up with an exception, and you have to start all over again.
This PR will change that.  So instead of raising, if we can't query a server to check it's lag, we'll simply log and pretend there is no lag.  If the server comes back up, it'll just be checked again the next time we can connect to it.
The code is pretty straightforward - I haven't 🎩  in production, but I feel like the safest course of …
=> Rescue failed connections on slave lag check, return 0

lib/lhm/throttler/slave_lag.rb, spec/unit/throttler/slave_lag_spec.rb
New option `:check_only` expects a lambda returning a connection config fragment for the specific slave; however, beware that credentials for the master are use to connect to this slave.
R: @sroysen, @jordanwheeler.
=> Optionally throttle based on the lag of a single slave

bin/lhm-spec-grants.sh, lhm.gemspec, lib/lhm/entangler.rb, lib/lhm/invoker.rb, spec/test_helper.rb, spec/unit/entangler_spec.rb
We've had a bunch of failed LHMs lately because of deadlocks creating/deleting the triggers.  It's especially frustrating when the whole thing runs, then it tries once to delete the triggers, times out after 8 seconds, and fails.  So then we have to restart the whole thing.
This puts the trigger creation/deletion in a retry block, so if the lock wait timeout is exceeded, the LHM will log, wait 1 second, and then try again. 10 times.  We chose 1 second of sleep and 10 retries to mimic PTOSC's behaviour - it never seems to have this problem.
I kind of tested it with an LHM locally, and the test may look kind of weird but it works as expected.
@insom @sroysen
=> Retry triggers on timeout exceeded error

lib/lhm/throttler/slave_lag.rb, spec/unit/throttler/slave_lag_spec.rb
Fixes https://github.com/Shopify/lhm/issues/16
In https://github.com/Shopify/lhm/pull/13 I ended up trying to fix a couple different things.  That did fix the case where we "stop slave" on a running node in the chain, but it broke in the case where we stop MySQL altogether on a slave.
One of the tests I added there was not very good, because it tested the outcome of a private method that I changed.  Had it tested the actual `lag` method that we care about, it would have caught the bug.  I updated that test, and added another regression test that catches the specific exception we saw in production.
@sroysen @insom
=> Handle checking slave lag when mysql is stopped

spec/unit/throttler/slave_lag_spec.rb
@insom i wrote this test earlier as a sanity check.  it passes.  so i think our problem is a connection to slaves issue, not necessarily a code issue.
anyways, i realized there wasn't a great test covering this logic specifically, so i figured i might as well add it to master.
=> add a test for max_current_slave_lag with multiple slaves

gemfiles/ar-5.0_mysql2.gemfile, lib/lhm/atomic_switcher.rb, lib/lhm/entangler.rb, lib/lhm/locked_switcher.rb, lib/lhm/migrator.rb, spec/integration/atomic_switcher_spec.rb, spec/integration/chunker_spec.rb, spec/integration/integration_helper.rb, spec/integration/lhm_spec.rb, spec/integration/locked_switcher_spec.rb, spec/integration/table_spec.rb, spec/unit/chunker_spec.rb, spec/unit/printer_spec.rb, spec/unit/throttler/slave_lag_spec.rb
I added an activerecord 5.0 gemfile, with the newer version of mysql2, which matches what we run in Shopify core.  All the tests now pass both here, and with the previous version of the Gemfile.  Nothing changed functionality wise, I basically just changed a bunch of stubbing stuff and simplified some of the tests as I went.  No actual code was touched.  But I didn't want to merge without at least opening a PR first 😄   You can try running the tests yourself if you want.
@sroysen @insom
=> Add activerecord 5.0 gemfile, update tests, fix deprecation warning

lib/lhm/throttler/slave_lag.rb, spec/unit/throttler/slave_lag_spec.rb
This will fix the `undefined method partition for nil:NilClass` error.  Now that `query_connection` returns a nil when it can't connect to the host, we need to handle that in the `format_hosts` method too.
@insom @sroysen
=> handle nil host in formatted_hosts

lib/lhm.rb, spec/integration/cleanup_spec.rb
This method will allow us to clean up an LHM that doesn't finish properly.  Instead of calling `Lhm.cleanup(true)`, which drops all `lhmt` trigger and all `lhm(a|n)` tables, you can now call`Lhm.cleanup_current_run(true, 'table_name')`.  This will drop `lhmt` triggers for your specific `table_name` only, and the `lhmn_table_name` table as well.  No `lhma` tables will be touched.
@sroysen @shuhaowu
=> Add Lhm.cleanup_current_run method

.gitignore, lib/lhm/chunker.rb, spec/integration/chunker_spec.rb, spec/integration/integration_helper.rb, spec/integration/lhm_spec.rb, spec/unit/chunker_spec.rb
This LHM will radically change the way that chunks of records are grabbed from the source table to be copied to the destination table.
Right now, LHMs work by copying fixed sets of primary keys, where the definition for the top id to copy in each chunk is simply the addition of the stride to the lower id of the chunk.
That has always been inefficient, even on tables using all mysql defaults (meaning, auto_increment_increment value of 1: primary keys grow just one by one), for several reasons:
1. Usual write patterns on any table are going to leave holes in them (when deleting records). 
With a fixed window of primary keys as before, LHMs were going to run ignorant of the real distribution of records in a table.
2. Gaps of primary keys in a table for any reason (for instance the insertion …
=> Change LHMs to use a non-fixed copy window

README.md, lib/lhm.rb, lib/lhm/throttler/slave_lag.rb, lib/lhm/throttler/time.rb
As the title says: Reduces the default size of a chunk to a more reasonable 2K.
=> Reduce the size of the default chunk to 2K

lib/lhm/throttler/slave_lag.rb
The original query didn't match anything on the cloud nodes, as they show `Binlog Dump GTID` in the process list. I just made it a wildcard instead.
=> The command is actually `Binlog Dump GTID` on GTID servers

Gemfile, Rakefile, shipit.yml
I had to add a Gemfile, which was previously in `.gitignore`. We're getting further away from something we can merge back into soundcloud/lhm so I'm not sure if this is a good idea.
After this I'll
- create a shipit stack
- create a github release for version 3.0.0.alpha
- deploy a build to packagecloud via shipit
=> Preparation for PackageCloud

lib/lhm.rb, lib/lhm/atomic_switcher.rb, spec/integration/atomic_switcher_spec.rb, spec/integration/chunker_spec.rb, spec/test_helper.rb
* Remove mysql2 conditionals: There should not be any Shopify apps using the mysql gem, everyone should
be using mysql2.
* Fix mocha/mini_test deprecation warning
* Replace Fixnum with Integer: https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html
=> Address some deprecation warnings

Gemfile.lock, README.md, dev.yml, lhm.gemspec, lib/lhm/atomic_switcher.rb, spec/integration/atomic_switcher_spec.rb, spec/test_helper.rb, spec/unit/atomic_switcher_spec.rb
I am considering refactoring the atomic_switch's
retry behavior. Before doing so, let's make sure we
have great test coverage everywhere. This adds
some tools to make that happen and adds test
coverage.
=> Bring atomic_switch_spec code coverage to 100%

Gemfile.lock, lhm.gemspec, lib/lhm/atomic_switcher.rb, lib/lhm/entangler.rb, lib/lhm/retry_helper.rb, spec/integration/atomic_switcher_spec.rb, spec/unit/entangler_spec.rb
These two classes both implementing a retry-on-exception pattern.
Chunker will be the third consumer of this pattern.
Let's make reusing this pattern very easy while making the implementation
consistent.
This change offers several improvements:
* No homegrown retry logic
* Retries now have more configuration choices
* Retries now backoff
* Better logging during retries
* Fixes a N+1 assertion in the test suite
* Fixes a slow unit test
* Stops usage of entangler.instance_variable_set
=> Unify Entangler and AtomicSwitcher retry interface

lib/lhm.rb, lib/lhm/cleanup/current.rb, lib/lhm/migration.rb, lib/lhm/timestamp.rb, spec/integration/cleanup_spec.rb
When an LHM worker fails, `cleanup_current_run` must be called to remove
the triggers and "new" tables (which start with lhmn_). The previous
behavior was to drop the table immediately. However, if this is an active
table, the InnoDB buffer pool can be full of pages related to this "lhmn_"
table. When it is dropped, this forces IBP to clear to those pages and can
cause MySQL to become unresponsive.
By instead renaming this table with the archive prefix (lhma_) when can let
the buffer unload relevant pages overtime, and then later, safely, drop the
archive tables as part of regular scheduled maintenance.
=> Rename lhmn_ tables to lhma_ to avoid IBP stalls

spec/integration/integration_helper.rb
Closes https://github.com/Shopify/lhm/issues/46.
This improves test isolation while also setting the stage to address
https://github.com/Shopify/lhm/issues/47 by shortening the timestamps
in "lhma" tables. Without this cleanup, and without the precision of those
timestamps, tests were failing reporting duplicate table names.
```
dev clone lhm
dev down
dev up
dev test
./dbdeployer/sandboxes/rsandbox_5_7_22/m
```
See no tables are left after test suite is run.
```
master [localhost] {msandbox} ((none)) > SELECT table_name FROM information_schema.tables WHERE table_schema = 'test';
Empty set (0.00 sec)
```
=> Cleanup tables after each test

lib/lhm/throttler/slave_lag.rb, spec/unit/throttler/slave_lag_spec.rb
The Billing team was trying to use the Slave Lag Throttler to run some LHMs and it wasn't behaving as expected. While investigating, we noticed a log statement like: 
"`Connecting to 35.***.***.31 on database:` "
which made us think that the `config` was missing the `database` entry. Turns out it was just the log statement that was incorrect/misleading (`config['database']` vs `config[:database]`).
I am proposing to fix this by symbolizing the keys in the config and using symbols to access the values. 
I added a test and also refactored a couple of the existing tests since the assertions in those tests were not being executed.
=> Slave lag throttler symbolize config keys

Gemfile.lock, lhm.gemspec, lib/lhm/sql_retry.rb
Given:
* retries are not configurable from outside the library yet (https://github.com/Shopify/lhm/issues/53)
* Shopify is the primary consumer of this library
When:
* Shopify cannot currently use retriable >=3 (https://github.com/Shopify/shopify/pull/167954)
Then:
* You get this PR!
The primary feature that we care about from the pre-3.0 release is https://github.com/kamui/retriable/pull/24
which targets subclasses of exceptions. Since we're loosing that, we'll just duplicate the error classes from which we might expect the errors we want to retry.
=> Loosen dependency on retriable gem

lib/lhm/sql_retry.rb
This new exception class popped up. Sadly we have to add it explicitly
because the version of retriable we can use in Shopify doesn't support
checking inheritance. And also sadly, this isn't customizable by consumers
of the gem, so we're doing it here.
=> Add more exception classes to retry

lib/lhm/sql_retry.rb
This PR adds a new exception class to the list of exceptions on which to retry the LHMs. We also do some cleanup and guard against uninitialized constant, because some of these exception classes might not be initialized in different apps or version of rails.
=> Improve exception error retry

CHANGELOG.md, Gemfile.lock, lib/lhm/version.rb
Bump up the version for LHM and also create a release related to this [patch](https://github.com/Shopify/lhm/pull/63).
=> Bump version for new exception class retry

Gemfile.lock, lib/lhm/cleanup/current.rb
These can fail due to lock wait timeouts also. They deserve retries.
Closes #65
=> Retry current cleanup

CHANGELOG.md, Gemfile.lock, lhm.gemspec, lib/lhm/sql_retry.rb, lib/lhm/version.rb
Now that we can confidently rely on `retriable > 3` we can remove the logic which checks if an exception is defined etc. and go back to matching on `StandardError` subclasses, by the text of the exception instead.
This will return the gem to being Rails agnostic and not relying on specific wrapped exceptions that other users may not have in their Rails apps.
=> Simplify LHM exception handling

lib/lhm/chunker.rb, lib/lhm/invoker.rb, spec/integration/chunker_spec.rb, spec/integration/lhm_spec.rb
It's not safe to perform the last step of LHM (the rename) if the triggers have been removed. Thankfully, this fork of LHM will avoid data corruption, thanks to https://github.com/Shopify/lhm/pull/23
However, we still _run_ the LHM to completion before giving up. This PR adds a `verifier` to options which can be used to check if LHM should continue to insert rows. This should result in less wasted work when triggers are dropped, with the side effect that LHM can be convinced to abort by manually dropping the triggers or by running `cleanup`.
=> Abort LHM early when triggers are removed during a copy

Gemfile.lock, lib/lhm/sql_retry.rb, lib/lhm/version.rb
Consider that `Unknown MySQL server host` errors may be transient due to transient DNS or networking errors, so retry them, as odd as that sounds.
=> Retry on 'Unknown MySQL server host' errors

lib/lhm/chunker.rb, lib/lhm/printer.rb, spec/unit/printer_spec.rb
Injecting a custom printer is useful to notify, for example, slack. I added a new method to notify the printer of exceptions that happen during execution, so we can also notify on those.
=> Add `exception` method to default printer

README.md, dbdeployer/install.sh, dev.yml, lib/lhm/throttler.rb, lib/lhm/throttler/threads_running.rb, spec/unit/throttler/threads_running_spec.rb
Sometimes you're in an environment where you can't connect to your replicas to use the `SlaveLag` (sic) throttler, but you want something better than the default `time` based one.
This throttler class will check the current threads running and exponentially back off (to a limit) if they are outside of a predefined range (defaults to `0..50`). This should slow down LHM if it appears to be overloading the database.
=> Threads Running Throttler

lib/lhm.rb, lib/lhm/railtie.rb, lib/lhm/test_support.rb
Core does this thing (https://github.com/Shopify/shopify/pull/50014) and we found that `Shopify/billing` would benefit from it too.
Rather than copy-paste the patch I decided to make it part of `Shopify/lhm`.
This should have zero impact on how migrations are run in production.
=> Run ALTER TABLE inline in tests

lib/lhm/migrator.rb, spec/integration/lhm_spec.rb
This should resolve issue #97
I don't believe the issue was that the NULL was improperly quoted. The issue was that col[:is_nullable] didn't return a boolean and instead returned "YES"/"NO". Updated the condition to be `unless col[:is_nullable] == "YES"`
=> Corrected is_nullable unless check in renaming column

lib/lhm/table.rb, spec/unit/table_spec.rb
From mysql 8 display attributes on fields are deprecated. This updates
constraint checks to allow for this.
https://dev.mysql.com/worklog/task/?id=13127
=> handle no display attribute on field

lib/lhm/migrator.rb, lib/lhm/table.rb, spec/integration/lhm_spec.rb
This PR adds logic to the `rename_column` method to keep the `comment` and `collate` values on rename.
> For column definition changes using CHANGE or MODIFY, the definition must include the data type and all attributes that should apply to the new column, other than index attributes such as PRIMARY KEY or UNIQUE. Attributes present in the original definition but not specified for the new definition are not carried forward. 
Source: https://dev.mysql.com/doc/refman/5.7/en/alter-table.html
https://github.com/Shopify/lhm/issues/85 is no longer valid, added a test to validate.
=> added comment and collate copying to rename_column

CHANGELOG.md, lib/lhm-shopify.rb, lib/lhm/version.rb
Added `lhm-shopify.rb` to avoid manually requiring `lhm` on gem usage
=> Release 3.3.6 (added lhm-shopify.rb)

lib/lhm.rb, spec/integration/cleanup_spec.rb
It would be useful for the end user to see what has actually happened when they run the clean up task. Right now, the way around this is to run cleanup with `run=false` first to see the "would delete blah blah blah..." output and then afterwards run it with `run=true`. However, the `run=true` option produces no output to confirm what has actually happened.
This PR adds simple output to show the names of the dropped triggers and tables when executing cleanup with run=true.
The test landscape in this gem isn't quite what I expected, so I'm not sure if I've added a test in the right place. My test feels more like a unit test in spirit but it seems like all of the cleanup flows are in `integration/cleanup_spec.rb` so I've added mine there.
=> print deleted trigger and table names to std out

spec/integration/atomic_switcher_spec.rb, spec/integration/chunk_insert_spec.rb, spec/integration/chunker_spec.rb, spec/integration/cleanup_spec.rb, spec/integration/entangler_spec.rb, spec/integration/lhm_spec.rb, spec/integration/lock_wait_timeout_spec.rb, spec/integration/locked_switcher_spec.rb, spec/integration/table_spec.rb, spec/unit/atomic_switcher_spec.rb, spec/unit/entangler_spec.rb, spec/unit/intersection_spec.rb, spec/unit/lhm_spec.rb, spec/unit/locked_switcher_spec.rb, spec/unit/migrator_spec.rb, spec/unit/sql_helper_spec.rb, spec/unit/table_spec.rb, spec/unit/throttler_spec.rb
Minitest has deprecated all the expectation methods (must_equal, must_be, ...) in the global `Object` namespace. Instead you're supposed to use the [_(value = nil, &block)](http://docs.seattlerb.org/minitest/Minitest/Spec/DSL/InstanceMethods.html) method which returns a value monad that has all of expectation methods available on it. The method is also aliased to `value` and `expect`, so these examples are basically identical:
```
_(1 + 1).must_equal(2)
value(1 + 1).must_equal(2)
expect(1 + 1).must_equal(2)
```
After talking to @tiwilliam, we decided to go with `value`.
=> Fix minitest deprecation warnings

lib/lhm.rb, lib/lhm/chunker.rb, lib/lhm/cleanup/current.rb, lib/lhm/entangler.rb, lib/lhm/migrator.rb, lib/lhm/printer.rb, spec/integration/cleanup_spec.rb, spec/integration/integration_helper.rb, spec/unit/printer_spec.rb, spec/unit/unit_helper.rb
LHM gem earlier did not print much of the log messages via the logger earlier. All it printed was the start of the class (Chunker, Entangler, AtomicSwitcher etc). 
In this PR I am adding the code so that LHM logs everything via the `logger` and not with `puts`. 
An example output of the LHM run of table to add a column is 
```
I, [2021-09-15T08:59:55.502850 #50456]  INFO -- : Starting LHM run on table=lhmn_table1
I, [2021-09-15T08:59:55.507802 #50456]  INFO -- : Starting run of class=Lhm::Migrator
I, [2021-09-15T08:59:55.516547 #50456]  INFO -- : Created destination table lhmn_table1
I, [2021-09-15T08:59:55.524681 #50456]  INFO -- : Starting run of class=Lhm::Entangler
I, [2021-09-15T08:59:55.534139 #50456]  INFO -- : Created triggers on #<Lhm::Table:0x00007fe6180af630>
I, …
```
=> Better logging to the LHM gem

.gitignore, lib/lhm.rb, lib/lhm/atomic_switcher.rb, lib/lhm/chunk_insert.rb, lib/lhm/chunker.rb, lib/lhm/cleanup/current.rb, lib/lhm/connection.rb, lib/lhm/entangler.rb, lib/lhm/invoker.rb, lib/lhm/sql_retry.rb, spec/integration/atomic_switcher_spec.rb, spec/integration/integration_helper.rb, spec/unit/chunker_spec.rb, spec/unit/connection_spec.rb, spec/unit/entangler_spec.rb
Created an `Lhm::Connection` class to remove confusing logic and ensure that SQLRetry isn't passed around unnecessarily, rendering `@connection` useless. 
The `Lhm.setup(@connection)` creates an `Lhm::Connection` instance with the ActiveRecord connection. In order to make this change as non-breaking as possible, I thought of using mass-delegation instead of inheritance. The problem was that every method that is not "handled" by the new `Lhm::Connection` should be delegated to the ActiveRecord connection.
I had to improvise a way to do that, so I came up with `lib/connection.rb:9-22`. It's a bit convoluted but achieves what I was looking for quite well. I had to wrap it in a `begin-end` for internal ruby-specific reasons, but if anyone has any better idea, I am trying to make this **as …
=> Added a `Connection` class to isolate SQLRetry

CHANGELOG.md, Rakefile, lib/lhm.rb, lib/lhm/chunk_insert.rb, lib/lhm/chunker.rb, lib/lhm/connection.rb, lib/lhm/sql_retry.rb, lib/lhm/version.rb, spec/integration/sql_retry/lock_wait_spec.rb, spec/integration/sql_retry/retry_with_proxysql_spec.rb, spec/unit/lhm_spec.rb
A regression was introduced where calling `Lhm.connection` would error when used before calling `Lhm.setup`. 
This fix can be found at `lib/lhm.rb:102`.
I added some tests to ensure that the LHM API would not experience further regressions
This led to a minor refactor of some other pieces of code that were excessively confusing.
This included renaming `options` to `retry_options` in the `Lhm::SqlRetry initializer` and added some logic to be able to hot-swap the ActiveRecord connection in `Lhm::Connection` without having to create a new one.
=> Fixed regression with Lhm.connection

Gemfile.lock, README.md, gemfiles/activerecord_5.2.gemfile.lock, gemfiles/activerecord_6.0.gemfile.lock, gemfiles/activerecord_6.1.gemfile.lock, gemfiles/activerecord_7.0.0.alpha2.gemfile.lock, lib/lhm/proxysql_helper.rb, lib/lhm/version.rb, spec/integration/proxysql_spec.rb, spec/unit/connection_spec.rb
Some internal tools have some requirements that an SQL query cannot start with a comment. Therefore, the tagging of the queries for ProxySQL have been changed to be after the query itself. 
Also added some documentation for gem upgrades for next contributors.
=> Changed ProxySQL annotation order + bump to 3.5.3

Gemfile.lock, docker-compose.yml, gemfiles/activerecord_5.2.gemfile.lock, gemfiles/activerecord_6.0.gemfile.lock, gemfiles/activerecord_6.1.gemfile.lock, gemfiles/activerecord_7.0.0.alpha2.gemfile.lock
`dev up` was failing following the transition to M1 Macbook Pros at the `docker pull` stage.
Added the stanza `platform: linux/amd64` for Percona services in `docker-compose.yml`. This ensures that the containers will be emulated with the right binaries (some performance hit but nothing too noticeable).
- `docker-compose.yml`
- The `Gemfiles-<version>.lock` added the `arm64-darwin` as a platform after running `dev up` on my machine. This will probably happen as new contributors pick up the project, so I decided to leave it
No
=> Added platform stanza for Percona images in docker-compose

README.md
http://openarkkit.googlecode.com seems to be broken, the new link for openarkkit is https://shlomi-noach.github.io/openarkkit/introduction.html
=> Update broken link for openarkkit in README

README.md, lib/lhm/throttler/threads_running.rb, spec/unit/throttler/threads_running_spec.rb
`Lhm::Throttler::ThreadsRunning` was missing the `#stride` method, which this PR fixes.
Tests and more usage examples were added as well.
=> Fix thread throttler #stride API

CHANGELOG.md, Gemfile.lock, gemfiles/activerecord_6.1.gemfile.lock, gemfiles/activerecord_7.0.gemfile.lock, gemfiles/activerecord_7.1.gemfile.lock, lib/lhm/chunker.rb, lib/lhm/version.rb, spec/fixtures/composite_primary_key_with_varchar_columns.ddl, spec/fixtures/composite_primary_key_with_varchar_columns_dest.ddl, spec/integration/chunker_spec.rb
We've encountered problems with composite primary keys, including varchar columns with values that have line breaks. The regex used to ignore primary key duplicate warnings can't handle the line breaks, which leads to LHM aborting completely safe migrations.
This PR rejiggers the warning matching to avoid this.
=> Handle composite primary keys with line breaks

.github/workflows/test.yml
docker compose syntax seems to no longer be supported on gh actions job runners (ref: https://github.com/Shopify/lhm/actions/runs/10220827210/job/28282002356)
Replaced with docker compose
=> Update docker compose command to be V2 compatible:

lib/lhm.rb, lib/lhm/invoker.rb, lib/lhm/migrator.rb, spec/fixtures/myisam_users.ddl, spec/integration/lhm_spec.rb
Adds a `force_default_engine` option. When enabled LHM will create the shadow table without copying the engine of the original table, meaning the migration will change the table to the default engine.
=> Add option to force tables to use default engine

lib/lhm/migrator.rb, spec/integration/lhm_spec.rb, spec/unit/migrator_spec.rb
Changes the default algorithm used for add/rename/remove column operations to `COPY` since it supports more use cases. It is slower, but that doesn't matter much since the changes are applied to empty tables.
Fixes #161.
=> Change default algorithm for add/rename/remove column operations

Gemfile.lock, lib/lhm/intersection.rb, lib/lhm/migration.rb, lib/lhm/migrator.rb, spec/integration/lhm_spec.rb
Currently if a table has any [generated columns](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html), the migration will fail as the Migrator will attempt to "write" to the generated column. This PR removes the columns from Intersection#common column names to prevent the write.
=> Add support for tables with generated columns

CHANGELOG.md, Gemfile.lock, gemfiles/activerecord_7.2.gemfile.lock, gemfiles/activerecord_8.0.gemfile.lock, gemfiles/activerecord_head.gemfile.lock, lib/lhm/entangler.rb, lib/lhm/version.rb, spec/unit/entangler_spec.rb
Changes the order we create triggers in to prevent the following scenario:
1. LHM creates shadow table.
2. LHM creates delete trigger.
3. LHM creates insert trigger.
4. Rows are inserted into the table and immediately updated.
5. LHM creates update trigger.
6. LHM copies over all rows.
7. LHM validates triggers, does the cutover, deletes the triggers, and is done.
Result: The inserts were replicated to the shadow table via the insert trigger, but the updates were not. Copying those rows failed since they already existed in the shadow table, and LHM ignored the error. We now have stale data after the migration finishes.
We ensure this can't happen by creating the update trigger first.
=> Create update before insert trigger
